### ISSUE TITLE
Bug: Far too many notifications

### ISSUE THREAD

**Issue by chriswessels** [graphops/subgraph-radio#71]
**Describe the bug**
Bug report from Sergey at P2P.org:

> We have enabled discord notifications today. We are getting 16-20 messages per minute from the subgraph-radio right now and already got around 25 notifications per each subgraph. We are running v0.1.6. Is there a way to fine-tune the notifications?

<img width="1760" alt="image" src="https://github.com/graphops/subgraph-radio/assets/2657600/05736b01-82e1-4bc3-bf6b-18160b67f9a0">

**Comment by chriswessels** [comment]
P2P is running 0.1.7 and is still reporting notifications spam: 
![image](https://github.com/graphops/subgraph-radio/assets/2657600/e10dd79c-21f6-4c2a-8ed2-3eb97f3f6077)

**Comment by hopeyen** [comment]
These are only divergent notifications now for matched<->diverged and notFound-> diverged. The screenshot indicates that repeated deployments became notFound for a bit and then diverged again.

This is the expected behavior I thought of; what do they prefer instead? We could
- ignore notFound->diverged altogether
- a configurable ratelimiter for each deployment   
- 1 notification for the results instead of individual notifications

**Comment by chriswessels** [comment]
We should possibly ignore transitions with `notFound` and then investigate why deployments transition to `notFound` if gossip should be flowing consistently.

Also think 1 notification with aggregate results is an improvement.

**Comment by cause1ove** [comment]
I think that disabling all of the notifications for notFound -> diverged state transition can lead to missing meaningful alerts. The one example I can think of is when the new subgraph-radio joins the network and has the information about the subgraph that was missing on the present peers.
However, the notifications about the subgraphs that were divergent before they got to notFound state is not expected by us since we already know that subgraph is diverged.
The ratelimit might work for us if we'll be able to limit the notifications to 1 message per day per subgraph.

**Comment by hopeyen** [comment]
Thanks for the feedbacks! Agree that NotFound->Diverged scenario could be useful. The reason why deployments transition to `NotFound` is precisely that gossip is not flowing consistently, likely due to boot node downtimes. There's related problems such as boot nodes on mainnet experience downtimes often, and gossip peers not connecting each other directly. 

I propose the following actions
- Look into discv5 discovery for the peers so the network doesn't rely on boot nodes for routing messages. 
  - This should've been working already, with boot nodes as the discv5 bootstrapping nodes though boot nodes don't have their discv5 udp discovery port exposed on prod server yet
- Add a ratelimit to each deployment when there's a new divergence result. We have a similar feature with upgrade intent message ratelimits so we can reference it here.
- Later on with the message pipeline issue #83 we will be adding daily summaries for metrics such as aggregated comparison results, and can then send an additional notification if desired

**Comment by chriswessels** [comment]
+1 thanks for the feedback @cause1ove! Good points. Agree with all your follow up @hopeyen, thank you.
